import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import { ListGroup, Figure, Image } from 'react-bootstrap';

export default function userDetail({ slug }) {

    const [data, setData] = React.useState(null)
    const [isLoading, setLoading] = React.useState(false)

    React.useEffect(() => {
        setLoading(true)
        fetch(`https://www.breakingbadapi.com/api/characters/${slug}`)
            .then((res) => res.json())
            .then((data) => {
                setData(data[0])
                setLoading(false)
            })
    }, [])

    if (isLoading) return <p>Loading...</p>
    if (!data) return <p>No profile data</p>

    console.log(data)

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Figure>
                    {/* USER IMAGE */}
                    <Figure.Image
                        className={styles.figure}
                        width={140}
                        height={140}
                        alt="140x140"
                        src={data.img}
                    />
                </Figure>

                <ListGroup as="ol" numbered>
                    {/* CHAR ID */}
                    <ListGroup.Item
                        as="li"
                        lassName="d-flex justify-content-between align-items-start"
                    >
                        <div className="ms-2 me-auto">
                            <div className="fw-bold">Char ID</div>
                            {data.char_id}
                        </div>
                    </ListGroup.Item>

                    {/* NAME SURNAME */}
                    <ListGroup.Item
                        as="li"
                        className="d-flex justify-content-between align-items-start"
                    >
                        <div className="ms-2 me-auto">
                            <div className="fw-bold">Name Surname</div>
                            {data.name}
                        </div>
                    </ListGroup.Item>

                    {/* NICKNAME */}
                    <ListGroup.Item
                        as="li"
                        className="d-flex justify-content-between align-items-start"
                    >
                        <div className="ms-2 me-auto">
                            <div className="fw-bold">Nickname</div>
                            {data.nickname}
                        </div>
                    </ListGroup.Item>

                    {/* BIRTHDAY */}
                    <ListGroup.Item
                        as="li"
                        className="d-flex justify-content-between align-items-start"
                    >
                        <div className="ms-2 me-auto">
                            <div className="fw-bold">Birthday</div>
                            {data.birthday}
                        </div>
                    </ListGroup.Item>

                    {/* CATEGORY */}
                    <ListGroup.Item
                        as="li"
                        className="d-flex justify-content-between align-items-start"
                    >
                        <div className="ms-2 me-auto">
                            <div className="fw-bold">Category</div>
                            {data.category}
                        </div>
                    </ListGroup.Item>

                    {/* BIRTDAY */}
                    <ListGroup.Item
                        as="li"
                        className="d-flex justify-content-between align-items-start"
                    >
                        <div className="ms-2 me-auto">
                            <div className="fw-bold">Birthday</div>
                            {data.birthday}
                        </div>
                    </ListGroup.Item>

                    {/* OCCUPATION */}
                    {
                        data.occupation.map((item, index) => {
                            return (
                                <ListGroup.Item
                                    key={index}
                                    as="li"
                                    className="d-flex justify-content-between align-items-start"
                                >
                                    <div className="ms-2 me-auto">
                                        <div className="fw-bold">Occupation {index + 1}</div>
                                        {item}
                                    </div>
                                </ListGroup.Item>
                            )
                        })
                    }

                    {/* PORTRAYED */}
                    <ListGroup.Item
                        as="li"
                        className="d-flex justify-content-between align-items-start"
                    >
                        <div className="ms-2 me-auto">
                            <div className="fw-bold">Portrayed</div>
                            {data.portrayed}
                        </div>
                    </ListGroup.Item>
                    <ListGroup.Item
                        as="li"
                        className="d-flex justify-content-between align-items-start"
                    >
                        <div className="ms-2 me-auto">
                            <div className="fw-bold">Status</div>
                            {data.status}
                        </div>
                    </ListGroup.Item>
                </ListGroup>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
export const getServerSideProps = async (ctx) => {
    const slug = ctx.params.slug;

    return {
        props: {
            slug: slug
        },
    };
};
