import Head from 'next/head'
import Link from "next/link";
import React from 'react'
import styles from '../styles/Home.module.css'
import { Table, Figure, Image } from 'react-bootstrap';

export default function Home({data}) {

  const [users, setUsers] = React.useState([]);

  React.useEffect(() => {
    getInformation();
  }, [])

  const getInformation = async () => {
    setUsers(data);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Table className={styles.table} striped bordered hover size="sm">
          {/* TABLE TITLES AREA */}
          <thead>
            <tr>
              <th className={styles.thread}>char_ID</th>
              <th className={styles.thread}>Image</th>
              <th className={styles.thread}>Name</th>
              <th className={styles.thread}>Birthday</th>
              <th className={styles.thread}>Nickname</th>
              <th className={styles.thread}>Category</th>
              <th className={styles.thread}>Portrayed</th>
              <th className={styles.thread}>Status</th>
              <th className={styles.thread}>Detail</th>
            </tr>
          </thead>

          {/* BODY OF VARIABLES */}
          <tbody>
            {
              users?.map((item, index) => {
                return (
                  <tr className={styles.tr} key={index}>
                    <td className={styles.td_two}>{item.char_id}</td>
                    <td className={styles.td}>
                      <Figure>
                        {/* USER IMAGE */}
                        <Figure.Image
                          className={styles.figure}
                          width={80}
                          height={80}
                          alt="80x80"
                          src={item.img}
                        />
                      </Figure>
                    </td>

                    {/* NAME */}
                    <td className={styles.td_two}>{item.name}</td>

                    {/* BIRTHDAY */}
                    <td className={styles.td}>
                      {
                        item.birthday != "Unknown" ?
                          item.birthday
                          :
                          "No variable"
                      }
                    </td>

                    {/* NICKNAME */}
                    <td className={styles.td_two}>{item.nickname}</td>

                    {/* CATEGORY */}
                    <td className={styles.td}>{item.category}</td>

                    {/* PORTRAYED */}
                    <td className={styles.td_two}>{item.portrayed}</td>

                    {/* STATUS */}
                    <td className={styles.td}>{item.status}</td>

                    {/* NAVIGATE */}
                    <div>
                      <Link href={`/${item.char_id}`}>
                        <p>Go Detail</p>
                      </Link>
                    </div>
                  </tr>
                )
              })
            }
          </tbody>
        </Table>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://www.breakingbadapi.com/api/characters`)
  const data = await res.json()

  // Pass data to the page via props
  return {
    props: {
      data
    },
  };
}
